### ISSUE TITLE
枠のサイズ指定追加の提案

### ISSUE THREAD

**Issue by daifuk-lana** [yuki-natsuno-vt/SpeechBubbleCSS#1]
ユーザ（チャンネル）名や、コメントの内容によっては横長になってしまいますので、幅の指定を出来るようにしておいた方が良いかと思います。全体の幅はcontentで指定するのが良いでしょうか。

例
yt-live-chat-text-message-renderer #content{
  width:200px;
}

**Comment by yuki-natsuno-vt** [comment]
デフォルトをautoにしておいて、固定したい人が任意の値を設定する記述にしておくとよいかもですね。
`width: auto; /*名前とメッセージの横幅 0～N px指定可能*/`

**Comment by yuki-natsuno-vt** [comment]
https://github.com/yuki-natsuno-vt/SpeechBubbleCSS/pull/2
Marge done.
